# Models

## Centralised FNN

In [ ]:
import os
os._exit(0)

In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_parquet(
    "/kaggle/working/CICIOT2023_FNN_READY.parquet"
)

print("Original Shape:", df.shape)

print("Total +inf:", np.isinf(df.drop(columns=["Label"])).sum().sum())

mask = np.isfinite(
    df.drop(columns=["Label"])
).all(axis=1)

df = df[mask].copy()

print("Cleaned Shape:", df.shape)

print(
    "Remaining inf:",
    np.isinf(df.drop(columns=["Label"])).sum().sum()
)

for col in df.columns:
    if col != "Label":
        df[col] = df[col].astype("float32")

df["Label"] = df["Label"].astype("int32")

print(df.dtypes.value_counts())

Original Shape: (21004851, 33)
Total +inf: 177
Cleaned Shape: (21004674, 33)
Remaining inf: 0
float32    32
int32       1
Name: count, dtype: int64


In [2]:
X = df.drop(columns=["Label"])
y = df["Label"]

print(X.shape)
print(y.shape)

(21004674, 32)
(21004674,)


In [3]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)
print("Splitting Done!")

Splitting Done!


In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)
print("Scaling Done")

Scaling Done


In [5]:
del X
del y
del df
del X_temp
del y_temp

import gc
gc.collect()

0

In [6]:
import torch

X_train = torch.tensor(X_train, dtype=torch.float32)
X_val   = torch.tensor(X_val, dtype=torch.float32)
X_test  = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train.values, dtype=torch.long)
y_val   = torch.tensor(y_val.values, dtype=torch.long)
y_test  = torch.tensor(y_test.values, dtype=torch.long)

print("Done Making Tensors!")

Done Making Tensors!


In [8]:
from torch.utils.data import TensorDataset, DataLoader

BATCH_SIZE = 10240
train_dataset = TensorDataset(
    X_train,
    y_train
)
val_dataset = TensorDataset(
    X_val,
    y_val
)
test_dataset = TensorDataset(
    X_test,
    y_test
)
train_loader = DataLoader(
    train_dataset,
    batch_size=10240,
    shuffle=True,
    num_workers=2,
    pin_memory=False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=10240,
    shuffle=False,
    num_workers=2,
    pin_memory=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=10240,
    shuffle=False,
    num_workers=2,
    pin_memory=False
)
print("DataLoaders Ready!")

DataLoaders Ready!


In [12]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = GeneralizedFNN().to(device)

criterion = FocalLoss(gamma=2)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-5
)

print(device)

cuda


In [13]:
print(device)
print(next(model.parameters()).device)
print(X_train.device)
print(y_train.device)

cuda
cuda:0
cpu
cpu


In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class FocalLoss(nn.Module):
    def __init__(self, gamma=2):
        super().__init__()
        self.gamma = gamma

    def forward(self, inputs, targets):

        ce_loss = F.cross_entropy(
            inputs,
            targets,
            reduction="none"
        )

        pt = torch.exp(-ce_loss)

        focal_loss = (
            (1 - pt) ** self.gamma
        ) * ce_loss

        return focal_loss.mean()

In [10]:
import torch.nn as nn

class GeneralizedFNN(nn.Module):

    def __init__(self):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(32, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(256, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(64, 8)
        )

    def forward(self, x):
        return self.network(x)

In [17]:
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

epochs = 30

for epoch in range(epochs):

    # --------------------
    # Training
    # --------------------
    model.train()

    running_loss = 0.0

    for X_batch, y_batch in train_loader:

        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        optimizer.zero_grad()

        outputs = model(X_batch)

        loss = criterion(outputs, y_batch)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)

    # --------------------
    # Validation
    # --------------------
    model.eval()

    y_true = []
    y_pred = []

    with torch.no_grad():

        for X_batch, y_batch in val_loader:

            X_batch = X_batch.to(device)

            outputs = model(X_batch)

            preds = torch.argmax(outputs, dim=1)

            y_true.extend(
                y_batch.cpu().numpy()
            )

            y_pred.extend(
                preds.cpu().numpy()
            )

    accuracy = accuracy_score(
        y_true,
        y_pred
    )

    precision, recall, f1, _ = (
        precision_recall_fscore_support(
            y_true,
            y_pred,
            average="weighted"
        )
    )
    best_f1=0
    if f1 > best_f1:
        best_f1 = f1
        torch.save(
            model.state_dict(),
            "best_fnn_focal_gamma2.pth")

    print(
        f"Epoch [{epoch+1}/{epochs}] | "
        f"Loss: {train_loss:.4f} | "
        f"Acc: {accuracy:.4f} | "
        f"Precision: {precision:.4f} | "
        f"Recall: {recall:.4f} | "
        f"F1: {f1:.4f}"
    )

Epoch [1/30] | Loss: 0.0950 | Acc: 0.8384 | Precision: 0.8316 | Recall: 0.8384 | F1: 0.8252
Epoch [2/30] | Loss: 0.0948 | Acc: 0.8396 | Precision: 0.8324 | Recall: 0.8396 | F1: 0.8282
Epoch [3/30] | Loss: 0.0947 | Acc: 0.8386 | Precision: 0.8324 | Recall: 0.8386 | F1: 0.8243
Epoch [4/30] | Loss: 0.0946 | Acc: 0.8394 | Precision: 0.8323 | Recall: 0.8394 | F1: 0.8272
Epoch [14/30] | Loss: 0.0938 | Acc: 0.8406 | Precision: 0.8337 | Recall: 0.8406 | F1: 0.8289
Epoch [15/30] | Loss: 0.0937 | Acc: 0.8389 | Precision: 0.8344 | Recall: 0.8389 | F1: 0.8221
Epoch [16/30] | Loss: 0.0937 | Acc: 0.8408 | Precision: 0.8341 | Recall: 0.8408 | F1: 0.8288
Epoch [17/30] | Loss: 0.0937 | Acc: 0.8411 | Precision: 0.8339 | Recall: 0.8411 | F1: 0.8313
Epoch [18/30] | Loss: 0.0936 | Acc: 0.8411 | Precision: 0.8343 | Recall: 0.8411 | F1: 0.8291
Epoch [19/30] | Loss: 0.0935 | Acc: 0.8412 | Precision: 0.8339 | Recall: 0.8412 | F1: 0.8314
Epoch [23/30] | Loss: 0.0934 | Acc: 0.8416 | Precision: 0.8345 | Recall: 0

In [19]:
model.eval()

test_preds = []
test_true = []

with torch.no_grad():

    for X_batch, y_batch in test_loader:

        X_batch = X_batch.to(device)

        outputs = model(X_batch)

        preds = torch.argmax(outputs, dim=1)

        test_preds.extend(
            preds.cpu().numpy()
        )

        test_true.extend(
            y_batch.numpy()
        )
from sklearn.metrics import (
    classification_report,
    confusion_matrix
)

target_names = [
    "Botnet",
    "BruteForce",
    "DDoS",
    "DoS",
    "Normal",
    "Recon",
    "Spoofing",
    "WebAttack"
]

print(
    classification_report(
        test_true,
        test_preds,
        target_names=target_names
    )
)

              precision    recall  f1-score   support

      Botnet       1.00      1.00      1.00    236226
  BruteForce       0.95      0.23      0.38      1252
        DDoS       0.84      0.94      0.89   1229195
         DoS       0.73      0.49      0.58    417849
      Normal       0.80      0.86      0.83    104731
       Recon       0.76      0.76      0.76     65546
    Spoofing       0.90      0.81      0.85     43606
   WebAttack       0.75      0.10      0.17      2063

    accuracy                           0.84   2100468
   macro avg       0.84      0.65      0.68   2100468
weighted avg       0.83      0.84      0.83   2100468



In [20]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    test_true,
    test_preds
)

print(cm)

[[ 235247       0     634      54     124     131      32       4]
 [      0     293       0       0     447     469      43       0]
 [    141       0 1153218   75821       4      10       1       0]
 [     34       0  214338  203467       3       4       3       0]
 [      1       4       0       0   89997   12333    2386      10]
 [      0       9       0       0   14629   49543    1353      12]
 [      8       0       1       2    6369    1812   35371      43]
 [      0       1       0       0     706     967     186     203]]
